# Sample Swarm config for Business Central
swarm:
  management:
    security-realms:
      ApplicationRealm: # almost the same as default config in WildFly 10.1.0.Final
        local-authentication:
          default-user: local
          allowed-users: local
          skip-group-loading: true
        properties-authentication:
          path: src/main/resources/application-users.properties
          plain-text: false
        properties-authorization:
          path: src/main/resources/application-roles.properties

datasource:
  management:
    wildfly:
      admin: admin

org:
  uberfire:
    ext:
      security:
        management:
          wildfly:
            cli:
              user: admin
